import { Alert } from "@/lib/types";

export const MOCK_ALERTS: Alert[] = [
  {
    id: 1,
    type: "Bullish",
    ticker: "MU",
    company: "Micron Technology",
    price: 422.95,
    strategy: "Bull Put Spread",
    strategyDesc: "credit spread, bullish to neutral outlook",
    legs: [
      { action: "Sell", qty: 1, ticker: "MU", expiry: "27 Feb 2026", strike: 380, type: "Put", price: 11.25 },
      { action: "Buy", qty: 1, ticker: "MU", expiry: "27 Feb 2026", strike: 375, type: "Put", price: 9.95 },
    ],
    maxProfit: "$130",
    maxProfitCond: "if MU stays above $380 at expiry",
    maxLoss: "$370",
    maxLossCond: "if MU falls below $375",
    breakeven: "$378.70",
    probProfit: 75,
    reasoning: [
      "MU is trading well above both strikes, and implied volatility is elevated (IV rank > 60), making credit spreads attractive.",
      "The short put is far out-of-the-money, giving a wide margin for error.",
      "You collect premium as long as MU doesn't drop sharply in the next 2 weeks.",
    ],
    time: "6:54 AM",
    aiConfidence: "High",
    isNew: true,
    current_price: 422.95,
    credit: 1.30,
    spread_width: 5,
    short_strike: 380,
    long_strike: 375,
    expiration: "2026-02-27",
    dte: 13,
    pop: 75,
    score: 72,
    short_delta: 0.12,
  },
  {
    id: 2,
    type: "Neutral",
    ticker: "MU",
    company: "Micron Technology",
    price: 422.95,
    strategy: "Short Put",
    strategyDesc: "income, bullish to neutral",
    legs: [
      { action: "Sell", qty: 1, ticker: "MU", expiry: "13 Feb 2026", strike: 380, type: "Put", price: 1.84 },
    ],
    maxProfit: "$184",
    maxProfitCond: "if MU stays above $380 by Friday",
    maxLoss: "$37,822",
    maxLossCond: "if MU falls to $0 (realistic risk only if below $380)",
    breakeven: "$378.16",
    probProfit: 90.6,
    reasoning: [
      "Very high probability of profit for a quick, short-term income play.",
      "You only risk assignment if MU drops over 10% in 2 days — extremely unlikely.",
    ],
    time: "6:54 AM",
    aiConfidence: "Very High",
    isNew: true,
    current_price: 422.95,
    credit: 1.84,
    spread_width: 5,
    short_strike: 380,
    long_strike: 375,
    expiration: "2026-02-13",
    dte: 2,
    pop: 90.6,
    score: 65,
    short_delta: 0.09,
  },
  {
    id: 3,
    type: "Bearish",
    ticker: "TSLA",
    company: "Tesla Inc",
    price: 328.50,
    strategy: "Bear Call Spread",
    strategyDesc: "credit spread, bearish to neutral outlook",
    legs: [
      { action: "Sell", qty: 1, ticker: "TSLA", expiry: "28 Feb 2026", strike: 360, type: "Call", price: 8.40 },
      { action: "Buy", qty: 1, ticker: "TSLA", expiry: "28 Feb 2026", strike: 370, type: "Call", price: 5.20 },
    ],
    netPremium: "$3.20/share ($320 total)",
    maxProfit: "$320",
    maxProfitCond: "if TSLA stays below $360 at expiry",
    maxLoss: "$680",
    maxLossCond: "if TSLA rises above $370",
    breakeven: "$363.20",
    probProfit: 68,
    reasoning: [
      "TSLA struggling at resistance near $340 with overbought RSI readings.",
      "IV elevated ahead of delivery numbers makes credit spreads attractive.",
      "Wide cushion between current price and short strike.",
    ],
    time: "7:12 AM",
    aiConfidence: "Medium",
    isNew: false,
    current_price: 328.50,
    credit: 3.20,
    spread_width: 10,
    short_strike: 360,
    long_strike: 370,
    expiration: "2026-02-28",
    dte: 14,
    pop: 68,
    score: 62,
    short_delta: 0.15,
  },
  {
    id: 4,
    type: "Bullish",
    ticker: "NVDA",
    company: "NVIDIA Corp",
    price: 875.30,
    strategy: "Long Call",
    strategyDesc: "directional, bullish outlook",
    legs: [
      { action: "Buy", qty: 1, ticker: "NVDA", expiry: "21 Mar 2026", strike: 900, type: "Call", price: 32.50 },
    ],
    maxProfit: "Unlimited",
    maxProfitCond: "unlimited upside above breakeven",
    maxLoss: "$3,250",
    maxLossCond: "premium paid if NVDA stays below $900",
    breakeven: "$932.50",
    probProfit: 42,
    reasoning: [
      "NVDA approaching earnings with strong institutional buying and bullish options flow.",
      "AI chip demand continues to accelerate — potential catalyst for a breakout above $900.",
      "Higher risk/reward play with asymmetric upside potential.",
    ],
    time: "7:30 AM",
    aiConfidence: "Medium",
    isNew: false,
    current_price: 875.30,
    credit: 0,
    spread_width: 0,
    short_strike: 900,
    long_strike: 900,
    expiration: "2026-03-21",
    dte: 35,
    pop: 42,
    score: 55,
    short_delta: 0.42,
  },
  {
    id: 5,
    type: "Bullish",
    ticker: "AAPL",
    company: "Apple Inc",
    price: 241.80,
    strategy: "Bull Call Spread",
    strategyDesc: "debit spread, bullish outlook",
    legs: [
      { action: "Buy", qty: 1, ticker: "AAPL", expiry: "28 Feb 2026", strike: 240, type: "Call", price: 6.20 },
      { action: "Sell", qty: 1, ticker: "AAPL", expiry: "28 Feb 2026", strike: 250, type: "Call", price: 2.80 },
    ],
    netPremium: "$3.40 debit ($340 total)",
    maxProfit: "$660",
    maxProfitCond: "if AAPL above $250 at expiry",
    maxLoss: "$340",
    maxLossCond: "debit paid if AAPL below $240",
    breakeven: "$243.40",
    probProfit: 55,
    reasoning: [
      "AAPL showing strong relative strength amid broader market uncertainty.",
      "Services revenue growth reaccelerating — positive for mid-term outlook.",
      "Defined risk with nearly 2:1 reward-to-risk ratio.",
    ],
    time: "8:01 AM",
    aiConfidence: "Medium-High",
    isNew: false,
    current_price: 241.80,
    credit: 0,
    spread_width: 10,
    short_strike: 240,
    long_strike: 250,
    expiration: "2026-02-28",
    dte: 14,
    pop: 55,
    score: 58,
    short_delta: 0.50,
  },
];
