#!/usr/bin/env python3
"""
Validate signal alignment between unified live scanner and backtester.

Compares signals generated by the unified live scan path (build_live_market_snapshot
→ strategy.generate_signals()) against the portfolio backtester over the same
30-day window using identical config + data.

Target: ≥90% signal overlap (same ticker, direction, DTE within 5 days).

Usage:
    PYTHONPATH=. python scripts/validate_signal_alignment.py [--days 30] [--config configs/paper_champion.yaml]
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Set, Tuple

import numpy as np
import pandas as pd
import yaml

# Add project root to sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine.portfolio_backtester import PortfolioBacktester
from shared.snapshot_builder import build_live_market_snapshot
from shared.strategy_factory import build_strategy_list
from strategies.base import Signal

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Signal fingerprint — used for comparison
# ---------------------------------------------------------------------------

def _signal_fingerprint(ticker: str, direction: str, dte: int, spread_type: str) -> Tuple:
    """Create a comparable fingerprint from signal attributes."""
    return (ticker.upper(), direction.lower(), dte, spread_type.lower())


def _fingerprints_match(fp1: Tuple, fp2: Tuple, dte_tolerance: int = 5) -> bool:
    """Check if two fingerprints match (ticker, direction exact; DTE within tolerance)."""
    ticker1, dir1, dte1, type1 = fp1
    ticker2, dir2, dte2, type2 = fp2
    return (
        ticker1 == ticker2
        and dir1 == dir2
        and abs(dte1 - dte2) <= dte_tolerance
        and type1 == type2
    )


# ---------------------------------------------------------------------------
# Backtester signal collection
# ---------------------------------------------------------------------------

def collect_backtester_signals(
    config: Dict, tickers: List[str], start_date: datetime, end_date: datetime,
) -> List[Dict]:
    """Run the backtester and collect all signals generated on each day.

    We subclass PortfolioBacktester to intercept signals before position limits
    filter them out — we want ALL signals, not just accepted ones.
    """
    strategies = []
    strat_instances = build_strategy_list(config)
    for strat in strat_instances:
        strategies.append((strat.__class__.__name__, strat))

    class SignalCollector(PortfolioBacktester):
        """Subclass that records all signals before filtering."""

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.all_signals: List[Dict] = []

        def run(self):
            self._load_data()

            all_dates: set = set()
            for ticker, pdf in self._price_data.items():
                all_dates.update(pdf.index.tolist())
            trading_dates = sorted(
                d for d in all_dates
                if self.start_date <= d.to_pydatetime().replace(tzinfo=None) <= self.end_date
            )

            for date_ts in trading_dates:
                date_dt = date_ts.to_pydatetime().replace(tzinfo=None)
                snapshot = self._build_market_snapshot(date_ts, date_dt)

                for name, strategy in self.strategies:
                    try:
                        signals = strategy.generate_signals(snapshot)
                        for sig in signals:
                            sig.signal_date = date_dt
                            dte = sig.dte if sig.dte else 0
                            self.all_signals.append({
                                "date": date_dt.strftime("%Y-%m-%d"),
                                "ticker": sig.ticker,
                                "strategy": sig.strategy_name,
                                "direction": sig.direction.value,
                                "dte": dte,
                                "credit": round(sig.net_credit, 4),
                                "score": round(sig.score, 2),
                                "spread_type": sig.metadata.get("trade_type", sig.metadata.get("spread_type", name)),
                                "profit_target_pct": sig.profit_target_pct,
                                "stop_loss_pct": sig.stop_loss_pct,
                            })
                    except Exception as e:
                        logger.debug("Backtester signal error %s on %s: %s", name, date_dt, e)

            return self.all_signals

    collector = SignalCollector(
        strategies=strategies,
        tickers=tickers,
        start_date=start_date,
        end_date=end_date,
        starting_capital=100_000,
    )

    return collector.run()


# ---------------------------------------------------------------------------
# Live scanner signal collection (using same data as backtester)
# ---------------------------------------------------------------------------

def collect_live_scanner_signals(
    config: Dict, tickers: List[str], start_date: datetime, end_date: datetime,
) -> List[Dict]:
    """Simulate the live scan path over the same date range.

    Uses the same yfinance data as the backtester, then builds MarketSnapshot
    via build_live_market_snapshot() and runs generate_signals().
    """
    import yfinance as yf
    from engine.regime import RegimeClassifier
    from shared.economic_calendar import EconomicCalendar
    from shared.indicators import calculate_iv_rank as _calc_ivr
    from strategies.pricing import calculate_rsi

    strat_instances = build_strategy_list(config)

    # Load data (same as backtester)
    warmup_days = 60
    fetch_start = start_date - timedelta(days=warmup_days)

    price_data = {}
    for ticker in tickers:
        try:
            raw = yf.download(
                ticker,
                start=fetch_start.strftime("%Y-%m-%d"),
                end=(end_date + timedelta(days=1)).strftime("%Y-%m-%d"),
                progress=False,
                auto_adjust=True,
            )
            if isinstance(raw.columns, pd.MultiIndex):
                raw.columns = raw.columns.get_level_values(0)
            if raw.index.tz is not None:
                raw.index = raw.index.tz_localize(None)
            price_data[ticker] = raw
        except Exception as e:
            logger.error("Failed to load %s: %s", ticker, e)

    # VIX data
    vix_data = None
    try:
        vix_fetch_start = start_date - timedelta(days=300)
        vix_raw = yf.download(
            "^VIX",
            start=vix_fetch_start.strftime("%Y-%m-%d"),
            end=(end_date + timedelta(days=1)).strftime("%Y-%m-%d"),
            progress=False,
            auto_adjust=True,
        )
        if isinstance(vix_raw.columns, pd.MultiIndex):
            vix_raw.columns = vix_raw.columns.get_level_values(0)
        if vix_raw.index.tz is not None:
            vix_raw.index = vix_raw.index.tz_localize(None)
        vix_data = vix_raw
    except Exception:
        pass

    # Economic calendar
    years = list(range(start_date.year, end_date.year + 1))
    calendar = EconomicCalendar(years=years)

    # Regime classifier
    regime_classifier = RegimeClassifier()

    # Build union of trading dates
    all_dates: set = set()
    for ticker, pdf in price_data.items():
        all_dates.update(pdf.index.tolist())
    trading_dates = sorted(
        d for d in all_dates
        if start_date <= d.to_pydatetime().replace(tzinfo=None) <= end_date
    )

    all_signals: List[Dict] = []

    for date_ts in trading_dates:
        date_dt = date_ts.to_pydatetime().replace(tzinfo=None)
        ref_date = date_dt.replace(tzinfo=timezone.utc)

        # Get VIX for this date
        vix_val = 20.0
        vix_history = None
        if vix_data is not None and not vix_data.empty:
            vix_close = vix_data["Close"].dropna()
            mask = vix_close.index <= date_ts
            vix_slice = vix_close[mask]
            if not vix_slice.empty:
                vix_val = float(vix_slice.iloc[-1])
                vix_history = vix_slice

        # IV rank
        iv_rank_val = 25.0
        if vix_data is not None and not vix_data.empty:
            vix_close = vix_data["Close"].dropna()
            window = vix_close.loc[vix_close.index <= date_ts].tail(252)
            if len(window) >= 20:
                try:
                    result = _calc_ivr(window, vix_val)
                    iv_rank_val = result["iv_rank"]
                except Exception:
                    pass

        # Upcoming + recent events
        upcoming_events = calendar.get_upcoming_events(days_ahead=3, reference_date=ref_date)
        recent_events = calendar.get_recent_events(days_back=2, reference_date=ref_date)

        for ticker in tickers:
            pdf = price_data.get(ticker)
            if pdf is None or pdf.empty:
                continue

            # Slice up to current date
            mask = pdf.index <= date_ts
            sliced = pdf.loc[mask]
            if sliced.empty:
                continue

            current_price = float(sliced["Close"].iloc[-1])

            # Build iv_data dict (live scanner format)
            iv_data = {"iv_rank": iv_rank_val, "iv_percentile": iv_rank_val, "current_iv": vix_val / 100}

            # Build technical_signals dict
            technical_signals = {"trend": "neutral", "rsi": 50.0}

            # Classify regime
            regime_val = None
            spy_close = sliced["Close"] if ticker.upper() == "SPY" else None
            if spy_close is not None:
                regime_val = regime_classifier.classify(vix_val, spy_close, date_ts).value

            # Build VIX DataFrame for snapshot builder
            vix_df_for_snapshot = None
            if vix_data is not None:
                vix_df_for_snapshot = vix_data.loc[vix_data.index <= date_ts]

            # Build snapshot using the live scanner path
            snapshot = build_live_market_snapshot(
                ticker=ticker,
                price_data=sliced,
                current_price=current_price,
                iv_data=iv_data,
                technical_signals=technical_signals,
                regime=regime_val,
                vix_data=vix_df_for_snapshot,
                upcoming_events=upcoming_events,
                recent_events=recent_events,
            )
            # Override date to match backtester (live snapshot uses datetime.now())
            snapshot.date = date_dt

            for strat in strat_instances:
                try:
                    signals = strat.generate_signals(snapshot)
                    for sig in signals:
                        sig.signal_date = date_dt
                        dte = sig.dte if sig.dte else 0
                        all_signals.append({
                            "date": date_dt.strftime("%Y-%m-%d"),
                            "ticker": sig.ticker,
                            "strategy": sig.strategy_name,
                            "direction": sig.direction.value,
                            "dte": dte,
                            "credit": round(sig.net_credit, 4),
                            "score": round(sig.score, 2),
                            "spread_type": sig.metadata.get("trade_type", sig.metadata.get("spread_type", strat.__class__.__name__)),
                            "profit_target_pct": sig.profit_target_pct,
                            "stop_loss_pct": sig.stop_loss_pct,
                        })
                except Exception as e:
                    logger.debug("Live scanner error %s on %s: %s", strat.__class__.__name__, date_dt, e)

    return all_signals


# ---------------------------------------------------------------------------
# Comparison logic
# ---------------------------------------------------------------------------

def compare_signals(
    backtester_signals: List[Dict],
    live_signals: List[Dict],
    dte_tolerance: int = 5,
) -> Dict[str, Any]:
    """Compare two signal sets and compute overlap metrics."""

    # Group by date
    bt_by_date: Dict[str, List[Dict]] = {}
    for s in backtester_signals:
        bt_by_date.setdefault(s["date"], []).append(s)

    live_by_date: Dict[str, List[Dict]] = {}
    for s in live_signals:
        live_by_date.setdefault(s["date"], []).append(s)

    all_dates = sorted(set(bt_by_date.keys()) | set(live_by_date.keys()))

    total_bt = len(backtester_signals)
    total_live = len(live_signals)
    matched_bt = 0
    matched_live = 0
    daily_results = []

    for date in all_dates:
        bt_sigs = bt_by_date.get(date, [])
        live_sigs = live_by_date.get(date, [])

        # Build fingerprints
        bt_fps = [
            _signal_fingerprint(s["ticker"], s["direction"], s["dte"], s["spread_type"])
            for s in bt_sigs
        ]
        live_fps = [
            _signal_fingerprint(s["ticker"], s["direction"], s["dte"], s["spread_type"])
            for s in live_sigs
        ]

        # Match: for each bt signal, find a matching live signal
        used_live = set()
        day_matched = 0
        for i, bt_fp in enumerate(bt_fps):
            for j, live_fp in enumerate(live_fps):
                if j not in used_live and _fingerprints_match(bt_fp, live_fp, dte_tolerance):
                    day_matched += 1
                    used_live.add(j)
                    break

        matched_bt += day_matched
        matched_live += len(used_live)

        daily_results.append({
            "date": date,
            "bt_signals": len(bt_sigs),
            "live_signals": len(live_sigs),
            "matched": day_matched,
        })

    # Compute overlap rates
    bt_overlap = (matched_bt / total_bt * 100) if total_bt > 0 else 100.0
    live_overlap = (matched_live / total_live * 100) if total_live > 0 else 100.0
    overall_overlap = min(bt_overlap, live_overlap)

    return {
        "total_backtester_signals": total_bt,
        "total_live_signals": total_live,
        "matched_bt_signals": matched_bt,
        "matched_live_signals": matched_live,
        "bt_overlap_pct": round(bt_overlap, 1),
        "live_overlap_pct": round(live_overlap, 1),
        "overall_overlap_pct": round(overall_overlap, 1),
        "target_met": overall_overlap >= 90.0,
        "daily_results": daily_results,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Validate signal alignment")
    parser.add_argument("--days", type=int, default=30, help="Number of days to compare")
    parser.add_argument("--config", type=str, default="configs/paper_champion.yaml",
                        help="Config file path")
    parser.add_argument("--dte-tolerance", type=int, default=5,
                        help="DTE tolerance for matching")
    parser.add_argument("--output", type=str, default="output/signal_alignment.json",
                        help="Output JSON file")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    # Load config
    with open(args.config) as f:
        config = yaml.safe_load(f)

    tickers = config.get("tickers", ["SPY"])
    end_date = datetime(2025, 12, 31)  # Use 2025 data (most dense in Polygon cache)
    start_date = end_date - timedelta(days=args.days)

    print(f"\n{'='*70}")
    print(f"SIGNAL ALIGNMENT VALIDATION")
    print(f"{'='*70}")
    print(f"Config:    {args.config}")
    print(f"Tickers:   {tickers}")
    print(f"Period:    {start_date.strftime('%Y-%m-%d')} → {end_date.strftime('%Y-%m-%d')}")
    print(f"DTE tol:   {args.dte_tolerance} days")
    print()

    # Collect backtester signals
    print("Phase 1: Collecting backtester signals...")
    bt_signals = collect_backtester_signals(config, tickers, start_date, end_date)
    print(f"  → {len(bt_signals)} signals from backtester")

    # Collect live scanner signals
    print("\nPhase 2: Collecting live scanner signals...")
    live_signals = collect_live_scanner_signals(config, tickers, start_date, end_date)
    print(f"  → {len(live_signals)} signals from live scanner")

    # Compare
    print("\nPhase 3: Comparing signals...")
    results = compare_signals(bt_signals, live_signals, args.dte_tolerance)

    # Print results
    print(f"\n{'='*70}")
    print("RESULTS")
    print(f"{'='*70}")
    print(f"Backtester signals:     {results['total_backtester_signals']}")
    print(f"Live scanner signals:   {results['total_live_signals']}")
    print(f"Matched (BT→Live):      {results['matched_bt_signals']} ({results['bt_overlap_pct']}%)")
    print(f"Matched (Live→BT):      {results['matched_live_signals']} ({results['live_overlap_pct']}%)")
    print(f"Overall overlap:        {results['overall_overlap_pct']}%")
    print(f"Target (≥90%):          {'PASS' if results['target_met'] else 'FAIL'}")

    # Strategy breakdown
    bt_by_strat = {}
    for s in bt_signals:
        bt_by_strat.setdefault(s["strategy"], []).append(s)
    live_by_strat = {}
    for s in live_signals:
        live_by_strat.setdefault(s["strategy"], []).append(s)

    print(f"\nPer-strategy signal counts:")
    all_strats = sorted(set(bt_by_strat.keys()) | set(live_by_strat.keys()))
    for strat in all_strats:
        bt_n = len(bt_by_strat.get(strat, []))
        live_n = len(live_by_strat.get(strat, []))
        print(f"  {strat:30s}  BT={bt_n:4d}  Live={live_n:4d}  diff={live_n - bt_n:+d}")

    # Exit param alignment check
    print(f"\nPer-trade exit param spot-check:")
    for source_name, sigs in [("Backtester", bt_signals), ("Live", live_signals)]:
        if not sigs:
            continue
        sample = sigs[0]
        print(f"  {source_name} sample: profit_target_pct={sample.get('profit_target_pct')}, "
              f"stop_loss_pct={sample.get('stop_loss_pct')}")

    # Save results
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {args.output}")

    print(f"\n{'='*70}")
    status = "PASS" if results["target_met"] else "FAIL"
    print(f"VERDICT: {status}")
    print(f"{'='*70}\n")

    return 0 if results["target_met"] else 1


if __name__ == "__main__":
    sys.exit(main())
